// convert-challenges-to-sentences.js
// const fs = require('fs');
// const path = require('path');
// const { ObjectId } = require('mongodb'); // hoặc mongoose.Types.ObjectId
import fs from 'fs';
import path from 'path';
import { ObjectId } from 'mongodb'; // hoặc mongoose.Types.ObjectId
// =============================================
// DỮ LIỆU GỐC (bạn paste toàn bộ mảng challenges vào đây)
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
// =============================================
const rawChallenges = [{
                    "id": 79986,
                    "position": 1,
                    "content": "According to legend, an emperor long ago declared that he would build a great wall",
                    "defaultInput": "",
                    "jsonContent": ["According", "to", "legend,", "an", "emperor", "long", "ago", "declared", "that", ["he would", "he'd"], "build", "a", "great", "wall"],
                    "solution": [["According"], ["to"], ["legend,"], ["an"], ["emperor"], ["long"], ["ago"], ["declared"], ["that"], ["he would", "he'd"], ["build"], ["a"], ["great"], ["wall"]],
                    "audioSrc": null,
                    "timeStart": 6.47,
                    "timeEnd": 12.39,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=1",
                    "discussionId": 79986,
                    "discussionName": "Lady Meng Jiang - challenge #1",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/79986\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/79986?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/79986",
                    "editUrl": null
                }, {
                    "id": 79987,
                    "position": 2,
                    "content": "spanning thousands of kilometers to protect his new empire and ensure his sustained power.",
                    "defaultInput": "",
                    "jsonContent": ["spanning", "thousands", "of", ["kilometers", "kilometres"], "to", "protect", "his", "new", "empire", "and", "ensure", "his", "sustained", "power."],
                    "solution": [["spanning"], ["thousands"], ["of"], ["kilometers", "kilometres"], ["to"], ["protect"], ["his"], ["new"], ["empire"], ["and"], ["ensure"], ["his"], ["sustained"], ["power."]],
                    "audioSrc": null,
                    "timeStart": 12.39,
                    "timeEnd": 18.99,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=2",
                    "discussionId": 79987,
                    "discussionName": "Lady Meng Jiang - challenge #2",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/79987\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/79987?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/79987",
                    "editUrl": null
                }, {
                    "id": 79988,
                    "position": 3,
                    "content": "He ordered many men across China to leave their homes and submit to the grueling labor required for its construction.",
                    "defaultInput": "",
                    "jsonContent": ["He", "ordered", "many", "men", "across", "China", "to", "leave", "their", "homes", "and", "submit", "to", "the", "grueling", ["labor", "labour"], "required", "for", "its", "construction."],
                    "solution": [["He"], ["ordered"], ["many"], ["men"], ["across"], ["China"], ["to"], ["leave"], ["their"], ["homes"], ["and"], ["submit"], ["to"], ["the"], ["grueling"], ["labor", "labour"], ["required"], ["for"], ["its"], ["construction."]],
                    "audioSrc": null,
                    "timeStart": 18.99,
                    "timeEnd": 25.96,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=3",
                    "discussionId": 79988,
                    "discussionName": "Lady Meng Jiang - challenge #3",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/79988\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/79988?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/79988",
                    "editUrl": null
                }, {
                    "id": 79989,
                    "position": 4,
                    "content": "As years passed and the wall grew, few returned home.",
                    "defaultInput": "",
                    "jsonContent": ["As", "years", "passed", "and", "the", "wall", "grew,", "few", "returned", "home."],
                    "solution": [["As"], ["years"], ["passed"], ["and"], ["the"], ["wall"], ["grew,"], ["few"], ["returned"], ["home."]],
                    "audioSrc": null,
                    "timeStart": 26.07,
                    "timeEnd": 30.94,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=4",
                    "discussionId": 79989,
                    "discussionName": "Lady Meng Jiang - challenge #4",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/79989\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/79989?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/79989",
                    "editUrl": null
                }, {
                    "id": 79990,
                    "position": 5,
                    "content": "Nestled in the foothills of a remote mountain,",
                    "defaultInput": "",
                    "jsonContent": ["Nestled", "in", "the", "foothills", "of", "a", "remote", "mountain,"],
                    "solution": [["Nestled"], ["in"], ["the"], ["foothills"], ["of"], ["a"], ["remote"], ["mountain,"]],
                    "audioSrc": null,
                    "timeStart": 31.1,
                    "timeEnd": 34.19,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=5",
                    "discussionId": 79990,
                    "discussionName": "Lady Meng Jiang - challenge #5",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/79990\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/79990?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/79990",
                    "editUrl": null
                }, {
                    "id": 79991,
                    "position": 6,
                    "content": "the Mengs and their neighbors, the Jiangs, hadn't yet had to worry about being drafted by the emperor's soldiers.",
                    "defaultInput": "the Mengs ",
                    "jsonContent": ["the", "Mengs", "and", "their", ["neighbors,", "neighbours"], "the", "Jiangs,", ["hadn't", "had not"], "yet", "had", "to", "worry", "about", "being", "drafted", "by", "the", "emperor's", "soldiers."],
                    "solution": [["the"], ["Mengs"], ["and"], ["their"], ["neighbors,", "neighbours"], ["the"], ["Jiangs,"], ["hadn't", "had not"], ["yet"], ["had"], ["to"], ["worry"], ["about"], ["being"], ["drafted"], ["by"], ["the"], ["emperor's"], ["soldiers."]],
                    "audioSrc": null,
                    "timeStart": 34.19,
                    "timeEnd": 40.4,
                    "hint": "Jiangs",
                    "hints": ["Jiangs"],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=6",
                    "discussionId": 79991,
                    "discussionName": "Lady Meng Jiang - challenge #6",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/79991\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/79991?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/79991",
                    "editUrl": null
                }, {
                    "id": 79992,
                    "position": 7,
                    "content": "One year, the Mengs grew gourds that flourished along their shared fence.",
                    "defaultInput": "",
                    "jsonContent": [["One", "1"], "year,", "the", "Mengs", "grew", "gourds", "that", "flourished", "along", "their", "shared", "fence."],
                    "solution": [["One", "1"], ["year,"], ["the"], ["Mengs"], ["grew"], ["gourds"], ["that"], ["flourished"], ["along"], ["their"], ["shared"], ["fence."]],
                    "audioSrc": null,
                    "timeStart": 40.66,
                    "timeEnd": 46.01,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=7",
                    "discussionId": 79992,
                    "discussionName": "Lady Meng Jiang - challenge #7",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/79992\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/79992?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/79992",
                    "editUrl": null
                }, {
                    "id": 79993,
                    "position": 8,
                    "content": "One particular gourd crossed the fence and extended into the Jiang's yard,",
                    "defaultInput": "",
                    "jsonContent": [["One", "1"], "particular", "gourd", "crossed", "the", "fence", "and", "extended", "into", "the", "Jiang's", "yard,"],
                    "solution": [["One", "1"], ["particular"], ["gourd"], ["crossed"], ["the"], ["fence"], ["and"], ["extended"], ["into"], ["the"], ["Jiang's"], ["yard,"]],
                    "audioSrc": null,
                    "timeStart": 46.01,
                    "timeEnd": 51.21,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=8",
                    "discussionId": 79993,
                    "discussionName": "Lady Meng Jiang - challenge #8",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/79993\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/79993?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/79993",
                    "editUrl": null
                }, {
                    "id": 79994,
                    "position": 9,
                    "content": "so they cared for it.",
                    "defaultInput": "",
                    "jsonContent": ["so", "they", "cared", "for", "it."],
                    "solution": [["so"], ["they"], ["cared"], ["for"], ["it."]],
                    "audioSrc": null,
                    "timeStart": 51.21,
                    "timeEnd": 52.77,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=9",
                    "discussionId": 79994,
                    "discussionName": "Lady Meng Jiang - challenge #9",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/79994\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/79994?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/79994",
                    "editUrl": null
                }, {
                    "id": 79995,
                    "position": 10,
                    "content": "The gourd grew to be the biggest of all.",
                    "defaultInput": "",
                    "jsonContent": ["The", "gourd", "grew", "to", "be", "the", "biggest", "of", "all."],
                    "solution": [["The"], ["gourd"], ["grew"], ["to"], ["be"], ["the"], ["biggest"], ["of"], ["all."]],
                    "audioSrc": null,
                    "timeStart": 52.77,
                    "timeEnd": 55.5,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=10",
                    "discussionId": 79995,
                    "discussionName": "Lady Meng Jiang - challenge #10",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/79995\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/79995?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/79995",
                    "editUrl": null
                }, {
                    "id": 79996,
                    "position": 11,
                    "content": "At harvest, the Mengs and the Jiangs decided to take equal halves.",
                    "defaultInput": "",
                    "jsonContent": ["At", "harvest,", "the", "Mengs", "and", "the", "Jiangs", "decided", "to", "take", "equal", "halves."],
                    "solution": [["At"], ["harvest,"], ["the"], ["Mengs"], ["and"], ["the"], ["Jiangs"], ["decided"], ["to"], ["take"], ["equal"], ["halves."]],
                    "audioSrc": null,
                    "timeStart": 55.5,
                    "timeEnd": 60.2,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=11",
                    "discussionId": 79996,
                    "discussionName": "Lady Meng Jiang - challenge #11",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/79996\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/79996?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/79996",
                    "editUrl": null
                }, {
                    "id": 79997,
                    "position": 12,
                    "content": "But as they went to split the gourd, something remarkable happened.",
                    "defaultInput": "",
                    "jsonContent": ["But", "as", "they", "went", "to", "split", "the", "gourd,", "something", "remarkable", "happened."],
                    "solution": [["But"], ["as"], ["they"], ["went"], ["to"], ["split"], ["the"], ["gourd,"], ["something"], ["remarkable"], ["happened."]],
                    "audioSrc": null,
                    "timeStart": 60.2,
                    "timeEnd": 65.26,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=12",
                    "discussionId": 79997,
                    "discussionName": "Lady Meng Jiang - challenge #12",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/79997\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/79997?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/79997",
                    "editUrl": null
                }, {
                    "id": 79998,
                    "position": 13,
                    "content": "It cracked open to reveal a beautiful baby curled inside, smiling up at them.",
                    "defaultInput": "",
                    "jsonContent": ["It", "cracked", "open", "to", "reveal", "a", "beautiful", "baby", "curled", "inside,", "smiling", "up", "at", "them."],
                    "solution": [["It"], ["cracked"], ["open"], ["to"], ["reveal"], ["a"], ["beautiful"], ["baby"], ["curled"], ["inside,"], ["smiling"], ["up"], ["at"], ["them."]],
                    "audioSrc": null,
                    "timeStart": 65.26,
                    "timeEnd": 71.97,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=13",
                    "discussionId": 79998,
                    "discussionName": "Lady Meng Jiang - challenge #13",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/79998\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/79998?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/79998",
                    "editUrl": null
                }, {
                    "id": 79999,
                    "position": 14,
                    "content": "They agreed to raise her together",
                    "defaultInput": "",
                    "jsonContent": ["They", "agreed", "to", "raise", "her", "together"],
                    "solution": [["They"], ["agreed"], ["to"], ["raise"], ["her"], ["together"]],
                    "audioSrc": null,
                    "timeStart": 71.97,
                    "timeEnd": 74.13,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=14",
                    "discussionId": 79999,
                    "discussionName": "Lady Meng Jiang - challenge #14",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/79999\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/79999?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/79999",
                    "editUrl": null
                }, {
                    "id": 80000,
                    "position": 15,
                    "content": "and named their magical, boundary-breaking daughter, Meng Jiang.",
                    "defaultInput": "",
                    "jsonContent": ["and", "named", "their", "magical,", ["boundary-breaking", "boundary breaking"], "daughter,", "Meng", "Jiang."],
                    "solution": [["and"], ["named"], ["their"], ["magical,"], ["boundary-breaking", "boundary breaking"], ["daughter,"], ["Meng"], ["Jiang."]],
                    "audioSrc": null,
                    "timeStart": 74.13,
                    "timeEnd": 78.97,
                    "hint": "Meng Jiang",
                    "hints": ["Meng Jiang"],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=15",
                    "discussionId": 80000,
                    "discussionName": "Lady Meng Jiang - challenge #15",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80000\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80000?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80000",
                    "editUrl": null
                }, {
                    "id": 80001,
                    "position": 16,
                    "content": "She grew into a virtuous, accomplished young woman who infused life with joy.",
                    "defaultInput": "",
                    "jsonContent": ["She", "grew", "into", "a", "virtuous,", "accomplished", "young", "woman", "who", "infused", "life", "with", "joy."],
                    "solution": [["She"], ["grew"], ["into"], ["a"], ["virtuous,"], ["accomplished"], ["young"], ["woman"], ["who"], ["infused"], ["life"], ["with"], ["joy."]],
                    "audioSrc": null,
                    "timeStart": 78.97,
                    "timeEnd": 84.69,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=16",
                    "discussionId": 80001,
                    "discussionName": "Lady Meng Jiang - challenge #16",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80001\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80001?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80001",
                    "editUrl": null
                }, {
                    "id": 80002,
                    "position": 17,
                    "content": "She cared for her elderly parents and their land with dedication.",
                    "defaultInput": "",
                    "jsonContent": ["She", "cared", "for", "her", "elderly", "parents", "and", "their", "land", "with", "dedication."],
                    "solution": [["She"], ["cared"], ["for"], ["her"], ["elderly"], ["parents"], ["and"], ["their"], ["land"], ["with"], ["dedication."]],
                    "audioSrc": null,
                    "timeStart": 84.69,
                    "timeEnd": 88.61,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=17",
                    "discussionId": 80002,
                    "discussionName": "Lady Meng Jiang - challenge #17",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80002\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80002?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80002",
                    "editUrl": null
                }, {
                    "id": 80003,
                    "position": 18,
                    "content": "But the surrounding world remained turbulent.",
                    "defaultInput": "",
                    "jsonContent": ["But", "the", "surrounding", "world", "remained", "turbulent."],
                    "solution": [["But"], ["the"], ["surrounding"], ["world"], ["remained"], ["turbulent."]],
                    "audioSrc": null,
                    "timeStart": 88.61,
                    "timeEnd": 91.8,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=18",
                    "discussionId": 80003,
                    "discussionName": "Lady Meng Jiang - challenge #18",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80003\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80003?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80003",
                    "editUrl": null
                }, {
                    "id": 80004,
                    "position": 19,
                    "content": "One day, Meng Jiang stumbled upon a young man hiding in the garden.",
                    "defaultInput": "",
                    "jsonContent": [["One", "1"], "day,", "Meng", "Jiang", "stumbled", "upon", "a", "young", "man", "hiding", "in", "the", "garden."],
                    "solution": [["One", "1"], ["day,"], ["Meng"], ["Jiang"], ["stumbled"], ["upon"], ["a"], ["young"], ["man"], ["hiding"], ["in"], ["the"], ["garden."]],
                    "audioSrc": null,
                    "timeStart": 91.95,
                    "timeEnd": 96.81,
                    "hint": "Meng Jiang",
                    "hints": ["Meng Jiang"],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=19",
                    "discussionId": 80004,
                    "discussionName": "Lady Meng Jiang - challenge #19",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80004\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80004?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80004",
                    "editUrl": null
                }, {
                    "id": 80005,
                    "position": 20,
                    "content": "The emperor's soldiers had come to conscript him into building the wall.",
                    "defaultInput": "",
                    "jsonContent": ["The", "emperor's", "soldiers", "had", "come", "to", "conscript", "him", "into", "building", "the", "wall."],
                    "solution": [["The"], ["emperor's"], ["soldiers"], ["had"], ["come"], ["to"], ["conscript"], ["him"], ["into"], ["building"], ["the"], ["wall."]],
                    "audioSrc": null,
                    "timeStart": 96.81,
                    "timeEnd": 101.39,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=20",
                    "discussionId": 80005,
                    "discussionName": "Lady Meng Jiang - challenge #20",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80005\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80005?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80005",
                    "editUrl": null
                }, {
                    "id": 80006,
                    "position": 21,
                    "content": "But he had an elderly mother to care for and knew that obeying the soldiers' orders would mean almost certain death,",
                    "defaultInput": "",
                    "jsonContent": ["But", ["he had", "he'd"], "an", "elderly", "mother", "to", "care", "for", "and", "knew", "that", "obeying", "the", "soldiers'", "orders", "would", "mean", "almost", "certain", "death,"],
                    "solution": [["But"], ["he had", "he'd"], ["an"], ["elderly"], ["mother"], ["to"], ["care"], ["for"], ["and"], ["knew"], ["that"], ["obeying"], ["the"], ["soldiers'"], ["orders"], ["would"], ["mean"], ["almost"], ["certain"], ["death,"]],
                    "audioSrc": null,
                    "timeStart": 101.39,
                    "timeEnd": 107.96,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=21",
                    "discussionId": 80006,
                    "discussionName": "Lady Meng Jiang - challenge #21",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80006\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80006?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80006",
                    "editUrl": null
                }, {
                    "id": 80007,
                    "position": 22,
                    "content": "so he escaped.",
                    "defaultInput": "",
                    "jsonContent": ["so", "he", "escaped."],
                    "solution": [["so"], ["he"], ["escaped."]],
                    "audioSrc": null,
                    "timeStart": 107.96,
                    "timeEnd": 109.59,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=22",
                    "discussionId": 80007,
                    "discussionName": "Lady Meng Jiang - challenge #22",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80007\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80007?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80007",
                    "editUrl": null
                }, {
                    "id": 80008,
                    "position": 23,
                    "content": "Meng Jiang and Fan Xiliang connected instantly,",
                    "defaultInput": "Meng Jiang and Fan Xiliang ",
                    "jsonContent": ["Meng", "Jiang", "and", "Fan", "Xiliang", "connected", "instantly,"],
                    "solution": [["Meng"], ["Jiang"], ["and"], ["Fan"], ["Xiliang"], ["connected"], ["instantly,"]],
                    "audioSrc": null,
                    "timeStart": 109.59,
                    "timeEnd": 114.51,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=23",
                    "discussionId": 80008,
                    "discussionName": "Lady Meng Jiang - challenge #23",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80008\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80008?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80008",
                    "editUrl": null
                }, {
                    "id": 80009,
                    "position": 24,
                    "content": "and soon enough, they married.",
                    "defaultInput": "",
                    "jsonContent": ["and", "soon", "enough,", "they", "married."],
                    "solution": [["and"], ["soon"], ["enough,"], ["they"], ["married."]],
                    "audioSrc": null,
                    "timeStart": 114.51,
                    "timeEnd": 116.72,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=24",
                    "discussionId": 80009,
                    "discussionName": "Lady Meng Jiang - challenge #24",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80009\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80009?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80009",
                    "editUrl": null
                }, {
                    "id": 80010,
                    "position": 25,
                    "content": "But their happiness wouldn't last long.",
                    "defaultInput": "",
                    "jsonContent": ["But", "their", "happiness", ["wouldn't", "would not"], "last", "long."],
                    "solution": [["But"], ["their"], ["happiness"], ["wouldn't", "would not"], ["last"], ["long."]],
                    "audioSrc": null,
                    "timeStart": 116.72,
                    "timeEnd": 119.48,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=25",
                    "discussionId": 80010,
                    "discussionName": "Lady Meng Jiang - challenge #25",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80010\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80010?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80010",
                    "editUrl": null
                }, {
                    "id": 80011,
                    "position": 26,
                    "content": "When the emperor's soldiers descended the next time,",
                    "defaultInput": "",
                    "jsonContent": ["When", "the", "emperor's", "soldiers", "descended", "the", "next", "time,"],
                    "solution": [["When"], ["the"], ["emperor's"], ["soldiers"], ["descended"], ["the"], ["next"], ["time,"]],
                    "audioSrc": null,
                    "timeStart": 119.48,
                    "timeEnd": 122.73,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=26",
                    "discussionId": 80011,
                    "discussionName": "Lady Meng Jiang - challenge #26",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80011\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80011?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80011",
                    "editUrl": null
                }, {
                    "id": 80012,
                    "position": 27,
                    "content": "they captured Fan Xiliang.",
                    "defaultInput": "",
                    "jsonContent": ["they", "captured", "Fan", "Xiliang."],
                    "solution": [["they"], ["captured"], ["Fan"], ["Xiliang."]],
                    "audioSrc": null,
                    "timeStart": 122.73,
                    "timeEnd": 125.61,
                    "hint": "Fan Xiliang",
                    "hints": ["Fan Xiliang"],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=27",
                    "discussionId": 80012,
                    "discussionName": "Lady Meng Jiang - challenge #27",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80012\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80012?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80012",
                    "editUrl": null
                }, {
                    "id": 80013,
                    "position": 28,
                    "content": "For months, she watched the horizon,",
                    "defaultInput": "",
                    "jsonContent": ["For", "months,", "she", "watched", "the", "horizon,"],
                    "solution": [["For"], ["months,"], ["she"], ["watched"], ["the"], ["horizon,"]],
                    "audioSrc": null,
                    "timeStart": 125.7,
                    "timeEnd": 128.26,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=28",
                    "discussionId": 80013,
                    "discussionName": "Lady Meng Jiang - challenge #28",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80013\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80013?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80013",
                    "editUrl": null
                }, {
                    "id": 80014,
                    "position": 29,
                    "content": "hoping the world would do right and deliver her love back to her safely.",
                    "defaultInput": "",
                    "jsonContent": ["hoping", "the", "world", "would", "do", "right", "and", "deliver", "her", "love", "back", "to", "her", "safely."],
                    "solution": [["hoping"], ["the"], ["world"], ["would"], ["do"], ["right"], ["and"], ["deliver"], ["her"], ["love"], ["back"], ["to"], ["her"], ["safely."]],
                    "audioSrc": null,
                    "timeStart": 128.26,
                    "timeEnd": 132.56,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=29",
                    "discussionId": 80014,
                    "discussionName": "Lady Meng Jiang - challenge #29",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80014\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80014?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80014",
                    "editUrl": null
                }, {
                    "id": 80015,
                    "position": 30,
                    "content": "But he never came.",
                    "defaultInput": "",
                    "jsonContent": ["But", "he", "never", "came."],
                    "solution": [["But"], ["he"], ["never"], ["came."]],
                    "audioSrc": null,
                    "timeStart": 132.56,
                    "timeEnd": 134.77,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=30",
                    "discussionId": 80015,
                    "discussionName": "Lady Meng Jiang - challenge #30",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80015\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80015?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80015",
                    "editUrl": null
                }, {
                    "id": 80016,
                    "position": 31,
                    "content": "And as the air grew frigid,",
                    "defaultInput": "",
                    "jsonContent": ["And", "as", "the", "air", "grew", "frigid,"],
                    "solution": [["And"], ["as"], ["the"], ["air"], ["grew"], ["frigid,"]],
                    "audioSrc": null,
                    "timeStart": 134.77,
                    "timeEnd": 137.05,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=31",
                    "discussionId": 80016,
                    "discussionName": "Lady Meng Jiang - challenge #31",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80016\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80016?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80016",
                    "editUrl": null
                }, {
                    "id": 80017,
                    "position": 32,
                    "content": "Meng Jiang's worries only grew,",
                    "defaultInput": "Meng Jiang's ",
                    "jsonContent": ["Meng", "Jiang's", "worries", "only", "grew,"],
                    "solution": [["Meng"], ["Jiang's"], ["worries"], ["only"], ["grew,"]],
                    "audioSrc": null,
                    "timeStart": 137.05,
                    "timeEnd": 139.61,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=32",
                    "discussionId": 80017,
                    "discussionName": "Lady Meng Jiang - challenge #32",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80017\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80017?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80017",
                    "editUrl": null
                }, {
                    "id": 80018,
                    "position": 33,
                    "content": "so she set out to find him herself.",
                    "defaultInput": "",
                    "jsonContent": ["so", "she", "set", "out", "to", "find", "him", "herself."],
                    "solution": [["so"], ["she"], ["set"], ["out"], ["to"], ["find"], ["him"], ["herself."]],
                    "audioSrc": null,
                    "timeStart": 139.61,
                    "timeEnd": 142.79,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=33",
                    "discussionId": 80018,
                    "discussionName": "Lady Meng Jiang - challenge #33",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80018\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80018?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80018",
                    "editUrl": null
                }, {
                    "id": 80019,
                    "position": 34,
                    "content": "Through bitter snow and howling winds, across rivers and mountains,",
                    "defaultInput": "",
                    "jsonContent": ["Through", "bitter", "snow", "and", "howling", "winds,", "across", "rivers", "and", "mountains,"],
                    "solution": [["Through"], ["bitter"], ["snow"], ["and"], ["howling"], ["winds,"], ["across"], ["rivers"], ["and"], ["mountains,"]],
                    "audioSrc": null,
                    "timeStart": 142.9,
                    "timeEnd": 147.25,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=34",
                    "discussionId": 80019,
                    "discussionName": "Lady Meng Jiang - challenge #34",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80019\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80019?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80019",
                    "editUrl": null
                }, {
                    "id": 80020,
                    "position": 35,
                    "content": "she undertook the dangerous journey that many others had been forced to complete.",
                    "defaultInput": "",
                    "jsonContent": ["she", "undertook", "the", "dangerous", "journey", "that", "many", "others", "had", "been", "forced", "to", "complete."],
                    "solution": [["she"], ["undertook"], ["the"], ["dangerous"], ["journey"], ["that"], ["many"], ["others"], ["had"], ["been"], ["forced"], ["to"], ["complete."]],
                    "audioSrc": null,
                    "timeStart": 147.25,
                    "timeEnd": 151.73,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=35",
                    "discussionId": 80020,
                    "discussionName": "Lady Meng Jiang - challenge #35",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80020\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80020?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80020",
                    "editUrl": null
                }, {
                    "id": 80021,
                    "position": 36,
                    "content": "Finally, she reached the construction site,",
                    "defaultInput": "",
                    "jsonContent": ["Finally,", "she", "reached", "the", "construction", "site,"],
                    "solution": [["Finally,"], ["she"], ["reached"], ["the"], ["construction"], ["site,"]],
                    "audioSrc": null,
                    "timeStart": 151.73,
                    "timeEnd": 154.01,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=36",
                    "discussionId": 80021,
                    "discussionName": "Lady Meng Jiang - challenge #36",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80021\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80021?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80021",
                    "editUrl": null
                }, {
                    "id": 80022,
                    "position": 37,
                    "content": "where thousands of workers toiled, day and night, to realize the emperor's vision.",
                    "defaultInput": "",
                    "jsonContent": ["where", "thousands", "of", "workers", "toiled,", "day", "and", "night,", "to", ["realize", "realise"], "the", "emperor's", "vision."],
                    "solution": [["where"], ["thousands"], ["of"], ["workers"], ["toiled,"], ["day"], ["and"], ["night,"], ["to"], ["realize", "realise"], ["the"], ["emperor's"], ["vision."]],
                    "audioSrc": null,
                    "timeStart": 154.01,
                    "timeEnd": 159.21,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=37",
                    "discussionId": 80022,
                    "discussionName": "Lady Meng Jiang - challenge #37",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80022\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80022?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80022",
                    "editUrl": null
                }, {
                    "id": 80023,
                    "position": 38,
                    "content": "Stealing into the fray, Meng Jiang whispered her husband's name to the workers",
                    "defaultInput": "",
                    "jsonContent": ["Stealing", "into", "the", "fray,", "Meng", "Jiang", "whispered", "her", "husband's", "name", "to", "the", "workers"],
                    "solution": [["Stealing"], ["into"], ["the"], ["fray,"], ["Meng"], ["Jiang"], ["whispered"], ["her"], ["husband's"], ["name"], ["to"], ["the"], ["workers"]],
                    "audioSrc": null,
                    "timeStart": 159.21,
                    "timeEnd": 164.8,
                    "hint": "Meng Jiang",
                    "hints": ["Meng Jiang"],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=38",
                    "discussionId": 80023,
                    "discussionName": "Lady Meng Jiang - challenge #38",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80023\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80023?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80023",
                    "editUrl": null
                }, {
                    "id": 80024,
                    "position": 39,
                    "content": "until, eventually, one man's eyes glimmered with recognition,",
                    "defaultInput": "",
                    "jsonContent": ["until,", "eventually,", ["one", "1"], "man's", "eyes", "glimmered", "with", "recognition,"],
                    "solution": [["until,"], ["eventually,"], ["one", "1"], ["man's"], ["eyes"], ["glimmered"], ["with"], ["recognition,"]],
                    "audioSrc": null,
                    "timeStart": 164.8,
                    "timeEnd": 168.99,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=39",
                    "discussionId": 80024,
                    "discussionName": "Lady Meng Jiang - challenge #39",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80024\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80024?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80024",
                    "editUrl": null
                }, {
                    "id": 80025,
                    "position": 40,
                    "content": "only for him to reveal the tragic news that Fan Xiliang had recently died.",
                    "defaultInput": "",
                    "jsonContent": ["only", "for", "him", "to", "reveal", "the", "tragic", "news", "that", "Fan", "Xiliang", "had", "recently", "died."],
                    "solution": [["only"], ["for"], ["him"], ["to"], ["reveal"], ["the"], ["tragic"], ["news"], ["that"], ["Fan"], ["Xiliang"], ["had"], ["recently"], ["died."]],
                    "audioSrc": null,
                    "timeStart": 168.99,
                    "timeEnd": 175,
                    "hint": "Fan Xiliang",
                    "hints": ["Fan Xiliang"],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=40",
                    "discussionId": 80025,
                    "discussionName": "Lady Meng Jiang - challenge #40",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80025\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80025?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80025",
                    "editUrl": null
                }, {
                    "id": 80026,
                    "position": 41,
                    "content": "He was rumored to be buried under the wall alongside many others.",
                    "defaultInput": "",
                    "jsonContent": ["He", "was", "rumored", "to", "be", "buried", "under", "the", "wall", "alongside", "many", "others."],
                    "solution": [["He"], ["was"], ["rumored"], ["to"], ["be"], ["buried"], ["under"], ["the"], ["wall"], ["alongside"], ["many"], ["others."]],
                    "audioSrc": null,
                    "timeStart": 175,
                    "timeEnd": 180.27,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=41",
                    "discussionId": 80026,
                    "discussionName": "Lady Meng Jiang - challenge #41",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80026\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80026?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80026",
                    "editUrl": null
                }, {
                    "id": 80027,
                    "position": 42,
                    "content": "Heartbroken beyond words, Meng Jiang could only weep.",
                    "defaultInput": "",
                    "jsonContent": ["Heartbroken", "beyond", "words,", "Meng", "Jiang", "could", "only", "weep."],
                    "solution": [["Heartbroken"], ["beyond"], ["words,"], ["Meng"], ["Jiang"], ["could"], ["only"], ["weep."]],
                    "audioSrc": null,
                    "timeStart": 180.27,
                    "timeEnd": 184.43,
                    "hint": "Meng Jiang",
                    "hints": ["Meng Jiang"],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=42",
                    "discussionId": 80027,
                    "discussionName": "Lady Meng Jiang - challenge #42",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80027\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80027?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80027",
                    "editUrl": null
                }, {
                    "id": 80028,
                    "position": 43,
                    "content": "As her tears filled the construction halls,",
                    "defaultInput": "",
                    "jsonContent": ["As", "her", "tears", "filled", "the", "construction", "halls,"],
                    "solution": [["As"], ["her"], ["tears"], ["filled"], ["the"], ["construction"], ["halls,"]],
                    "audioSrc": null,
                    "timeStart": 184.43,
                    "timeEnd": 187.37,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=43",
                    "discussionId": 80028,
                    "discussionName": "Lady Meng Jiang - challenge #43",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80028\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80028?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80028",
                    "editUrl": null
                }, {
                    "id": 80029,
                    "position": 44,
                    "content": "seeped into the cracks of the wall, and soaked its stone,",
                    "defaultInput": "",
                    "jsonContent": ["seeped", "into", "the", "cracks", "of", "the", "wall,", "and", "soaked", "its", "stone,"],
                    "solution": [["seeped"], ["into"], ["the"], ["cracks"], ["of"], ["the"], ["wall,"], ["and"], ["soaked"], ["its"], ["stone,"]],
                    "audioSrc": null,
                    "timeStart": 187.37,
                    "timeEnd": 190.85,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=44",
                    "discussionId": 80029,
                    "discussionName": "Lady Meng Jiang - challenge #44",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80029\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80029?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80029",
                    "editUrl": null
                }, {
                    "id": 80030,
                    "position": 45,
                    "content": "whole portions crumbled and washed away in the flood of her grief.",
                    "defaultInput": "",
                    "jsonContent": ["whole", "portions", "crumbled", "and", "washed", "away", "in", "the", "flood", "of", "her", "grief."],
                    "solution": [["whole"], ["portions"], ["crumbled"], ["and"], ["washed"], ["away"], ["in"], ["the"], ["flood"], ["of"], ["her"], ["grief."]],
                    "audioSrc": null,
                    "timeStart": 190.85,
                    "timeEnd": 195.46,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=45",
                    "discussionId": 80030,
                    "discussionName": "Lady Meng Jiang - challenge #45",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80030\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80030?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80030",
                    "editUrl": null
                }, {
                    "id": 80031,
                    "position": 46,
                    "content": "Livid, the emperor ordered that the person who'd sabotaged his grand project be captured",
                    "defaultInput": "",
                    "jsonContent": ["Livid,", "the", "emperor", "ordered", "that", "the", "person", "who'd", "sabotaged", "his", "grand", "project", "be", "captured"],
                    "solution": [["Livid,"], ["the"], ["emperor"], ["ordered"], ["that"], ["the"], ["person"], ["who'd"], ["sabotaged"], ["his"], ["grand"], ["project"], ["be"], ["captured"]],
                    "audioSrc": null,
                    "timeStart": 196.29,
                    "timeEnd": 202.09,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=46",
                    "discussionId": 80031,
                    "discussionName": "Lady Meng Jiang - challenge #46",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80031\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80031?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80031",
                    "editUrl": null
                }, {
                    "id": 80032,
                    "position": 47,
                    "content": "and brought to his palace for punishment.",
                    "defaultInput": "",
                    "jsonContent": ["and", "brought", "to", "his", "palace", "for", "punishment."],
                    "solution": [["and"], ["brought"], ["to"], ["his"], ["palace"], ["for"], ["punishment."]],
                    "audioSrc": null,
                    "timeStart": 202.09,
                    "timeEnd": 204.3,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=47",
                    "discussionId": 80032,
                    "discussionName": "Lady Meng Jiang - challenge #47",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80032\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80032?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80032",
                    "editUrl": null
                }, {
                    "id": 80033,
                    "position": 48,
                    "content": "But when he beheld the otherworldly beauty and virtue Meng Jiang radiated,",
                    "defaultInput": "",
                    "jsonContent": ["But", "when", "he", "beheld", "the", "otherworldly", "beauty", "and", "virtue", "Meng", "Jiang", "radiated,"],
                    "solution": [["But"], ["when"], ["he"], ["beheld"], ["the"], ["otherworldly"], ["beauty"], ["and"], ["virtue"], ["Meng"], ["Jiang"], ["radiated,"]],
                    "audioSrc": null,
                    "timeStart": 204.3,
                    "timeEnd": 209.82,
                    "hint": "Meng Jiang",
                    "hints": ["Meng Jiang"],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=48",
                    "discussionId": 80033,
                    "discussionName": "Lady Meng Jiang - challenge #48",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80033\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80033?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80033",
                    "editUrl": null
                }, {
                    "id": 80034,
                    "position": 49,
                    "content": "his plan changed.",
                    "defaultInput": "",
                    "jsonContent": ["his", "plan", "changed."],
                    "solution": [["his"], ["plan"], ["changed."]],
                    "audioSrc": null,
                    "timeStart": 209.82,
                    "timeEnd": 211.66,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=49",
                    "discussionId": 80034,
                    "discussionName": "Lady Meng Jiang - challenge #49",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80034\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80034?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80034",
                    "editUrl": null
                }, {
                    "id": 80035,
                    "position": 50,
                    "content": "Leering at the devastated widow,",
                    "defaultInput": "",
                    "jsonContent": ["Leering", "at", "the", "devastated", "widow,"],
                    "solution": [["Leering"], ["at"], ["the"], ["devastated"], ["widow,"]],
                    "audioSrc": null,
                    "timeStart": 211.66,
                    "timeEnd": 214.06,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=50",
                    "discussionId": 80035,
                    "discussionName": "Lady Meng Jiang - challenge #50",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80035\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80035?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80035",
                    "editUrl": null
                }, {
                    "id": 80036,
                    "position": 51,
                    "content": "the emperor instead suggested that she become one of his imperial concubines.",
                    "defaultInput": "",
                    "jsonContent": ["the", "emperor", "instead", "suggested", "that", "she", "become", ["one", "1"], "of", "his", "imperial", "concubines."],
                    "solution": [["the"], ["emperor"], ["instead"], ["suggested"], ["that"], ["she"], ["become"], ["one", "1"], ["of"], ["his"], ["imperial"], ["concubines."]],
                    "audioSrc": null,
                    "timeStart": 214.06,
                    "timeEnd": 219.55,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=51",
                    "discussionId": 80036,
                    "discussionName": "Lady Meng Jiang - challenge #51",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80036\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80036?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80036",
                    "editUrl": null
                }, {
                    "id": 80037,
                    "position": 52,
                    "content": "She had few options,",
                    "defaultInput": "",
                    "jsonContent": [["She had", "She'd"], "few", "options,"],
                    "solution": [["She had", "She'd"], ["few"], ["options,"]],
                    "audioSrc": null,
                    "timeStart": 219.55,
                    "timeEnd": 221.4,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=52",
                    "discussionId": 80037,
                    "discussionName": "Lady Meng Jiang - challenge #52",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80037\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80037?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80037",
                    "editUrl": null
                }, {
                    "id": 80038,
                    "position": 53,
                    "content": "but she realized she could leverage the wretched proposal",
                    "defaultInput": "",
                    "jsonContent": ["but", "she", ["realized", "realised"], "she", "could", "leverage", "the", "wretched", "proposal"],
                    "solution": [["but"], ["she"], ["realized", "realised"], ["she"], ["could"], ["leverage"], ["the"], ["wretched"], ["proposal"]],
                    "audioSrc": null,
                    "timeStart": 221.4,
                    "timeEnd": 225.31,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=53",
                    "discussionId": 80038,
                    "discussionName": "Lady Meng Jiang - challenge #53",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80038\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80038?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80038",
                    "editUrl": null
                }, {
                    "id": 80039,
                    "position": 54,
                    "content": "to honor Fan Xiliang and humiliate the emperor.",
                    "defaultInput": "",
                    "jsonContent": ["to", ["honor", "honour"], "Fan", "Xiliang", "and", "humiliate", "the", "emperor."],
                    "solution": [["to"], ["honor", "honour"], ["Fan"], ["Xiliang"], ["and"], ["humiliate"], ["the"], ["emperor."]],
                    "audioSrc": null,
                    "timeStart": 225.31,
                    "timeEnd": 229.35,
                    "hint": "Fan Xiliang",
                    "hints": ["Fan Xiliang"],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=54",
                    "discussionId": 80039,
                    "discussionName": "Lady Meng Jiang - challenge #54",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80039\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80039?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80039",
                    "editUrl": null
                }, {
                    "id": 80040,
                    "position": 55,
                    "content": "She said she agreed,",
                    "defaultInput": "",
                    "jsonContent": ["She", "said", "she", "agreed,"],
                    "solution": [["She"], ["said"], ["she"], ["agreed,"]],
                    "audioSrc": null,
                    "timeStart": 229.35,
                    "timeEnd": 231.35,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=55",
                    "discussionId": 80040,
                    "discussionName": "Lady Meng Jiang - challenge #55",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80040\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80040?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80040",
                    "editUrl": null
                }, {
                    "id": 80041,
                    "position": 56,
                    "content": "but only if the emperor gave her deceased husband a grand funeral",
                    "defaultInput": "",
                    "jsonContent": ["but", "only", "if", "the", "emperor", "gave", "her", "deceased", "husband", "a", "grand", "funeral"],
                    "solution": [["but"], ["only"], ["if"], ["the"], ["emperor"], ["gave"], ["her"], ["deceased"], ["husband"], ["a"], ["grand"], ["funeral"]],
                    "audioSrc": null,
                    "timeStart": 231.35,
                    "timeEnd": 235.55,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=56",
                    "discussionId": 80041,
                    "discussionName": "Lady Meng Jiang - challenge #56",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80041\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80041?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80041",
                    "editUrl": null
                }, {
                    "id": 80042,
                    "position": 57,
                    "content": "and that the emperor attend dressed in the traditional mourning attire he would wear had Fan Xiliang been his own father.",
                    "defaultInput": "",
                    "jsonContent": ["and", "that", "the", "emperor", "attend", "dressed", "in", "the", "traditional", "mourning", "attire", ["he would", "he'd"], "wear", "had", "Fan", "Xiliang", "been", "his", "own", "father."],
                    "solution": [["and"], ["that"], ["the"], ["emperor"], ["attend"], ["dressed"], ["in"], ["the"], ["traditional"], ["mourning"], ["attire"], ["he would", "he'd"], ["wear"], ["had"], ["Fan"], ["Xiliang"], ["been"], ["his"], ["own"], ["father."]],
                    "audioSrc": null,
                    "timeStart": 235.55,
                    "timeEnd": 243.31,
                    "hint": "Fan Xiliang",
                    "hints": ["Fan Xiliang"],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=57",
                    "discussionId": 80042,
                    "discussionName": "Lady Meng Jiang - challenge #57",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80042\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80042?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80042",
                    "editUrl": null
                }, {
                    "id": 80043,
                    "position": 58,
                    "content": "The emperor begrudgingly made the arrangements",
                    "defaultInput": "",
                    "jsonContent": ["The", "emperor", "begrudgingly", "made", "the", "arrangements"],
                    "solution": [["The"], ["emperor"], ["begrudgingly"], ["made"], ["the"], ["arrangements"]],
                    "audioSrc": null,
                    "timeStart": 243.31,
                    "timeEnd": 246.41,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=58",
                    "discussionId": 80043,
                    "discussionName": "Lady Meng Jiang - challenge #58",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80043\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80043?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80043",
                    "editUrl": null
                }, {
                    "id": 80044,
                    "position": 59,
                    "content": "and Meng Jiang bid her beloved farewell.",
                    "defaultInput": "and Meng Jiang ",
                    "jsonContent": ["and", "Meng", "Jiang", "bid", "her", "beloved", "farewell."],
                    "solution": [["and"], ["Meng"], ["Jiang"], ["bid"], ["her"], ["beloved"], ["farewell."]],
                    "audioSrc": null,
                    "timeStart": 246.41,
                    "timeEnd": 249.98,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=59",
                    "discussionId": 80044,
                    "discussionName": "Lady Meng Jiang - challenge #59",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80044\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80044?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80044",
                    "editUrl": null
                }, {
                    "id": 80045,
                    "position": 60,
                    "content": "Finally, with her wish carried out,",
                    "defaultInput": "",
                    "jsonContent": ["Finally,", "with", "her", "wish", "carried", "out,"],
                    "solution": [["Finally,"], ["with"], ["her"], ["wish"], ["carried"], ["out,"]],
                    "audioSrc": null,
                    "timeStart": 250.11,
                    "timeEnd": 252.71,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=60",
                    "discussionId": 80045,
                    "discussionName": "Lady Meng Jiang - challenge #60",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80045\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80045?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80045",
                    "editUrl": null
                }, {
                    "id": 80046,
                    "position": 61,
                    "content": "she refused to either submit to the emperor,",
                    "defaultInput": "",
                    "jsonContent": ["she", "refused", "to", "either", "submit", "to", "the", "emperor,"],
                    "solution": [["she"], ["refused"], ["to"], ["either"], ["submit"], ["to"], ["the"], ["emperor,"]],
                    "audioSrc": null,
                    "timeStart": 252.71,
                    "timeEnd": 255.61,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=61",
                    "discussionId": 80046,
                    "discussionName": "Lady Meng Jiang - challenge #61",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80046\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80046?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80046",
                    "editUrl": null
                }, {
                    "id": 80047,
                    "position": 62,
                    "content": "who now awaited her in his palace, or to face his punishment.",
                    "defaultInput": "",
                    "jsonContent": ["who", "now", "awaited", "her", "in", "his", "palace,", "or", "to", "face", "his", "punishment."],
                    "solution": [["who"], ["now"], ["awaited"], ["her"], ["in"], ["his"], ["palace,"], ["or"], ["to"], ["face"], ["his"], ["punishment."]],
                    "audioSrc": null,
                    "timeStart": 255.61,
                    "timeEnd": 260.05,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=62",
                    "discussionId": 80047,
                    "discussionName": "Lady Meng Jiang - challenge #62",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80047\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80047?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80047",
                    "editUrl": null
                }, {
                    "id": 80048,
                    "position": 63,
                    "content": "Instead, she cast herself into the nearby water,",
                    "defaultInput": "",
                    "jsonContent": ["Instead,", "she", "cast", "herself", "into", "the", "nearby", "water,"],
                    "solution": [["Instead,"], ["she"], ["cast"], ["herself"], ["into"], ["the"], ["nearby"], ["water,"]],
                    "audioSrc": null,
                    "timeStart": 260.37,
                    "timeEnd": 264.47,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=63",
                    "discussionId": 80048,
                    "discussionName": "Lady Meng Jiang - challenge #63",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80048\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80048?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80048",
                    "editUrl": null
                }, {
                    "id": 80049,
                    "position": 64,
                    "content": "as all-enveloping as her own tears, never to emerge again.",
                    "defaultInput": "",
                    "jsonContent": ["as", ["all-enveloping", "all enveloping"], "as", "her", "own", "tears,", "never", "to", "emerge", "again."],
                    "solution": [["as"], ["all-enveloping", "all enveloping"], ["as"], ["her"], ["own"], ["tears,"], ["never"], ["to"], ["emerge"], ["again."]],
                    "audioSrc": null,
                    "timeStart": 264.47,
                    "timeEnd": 268.87,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=64",
                    "discussionId": 80049,
                    "discussionName": "Lady Meng Jiang - challenge #64",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80049\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80049?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80049",
                    "editUrl": null
                }, {
                    "id": 80050,
                    "position": 65,
                    "content": "She had left an unjust world as mysteriously as she'd entered it.",
                    "defaultInput": "",
                    "jsonContent": [["She had", "She'd"], "left", "an", "unjust", "world", "as", "mysteriously", "as", "she'd", "entered", "it."],
                    "solution": [["She had", "She'd"], ["left"], ["an"], ["unjust"], ["world"], ["as"], ["mysteriously"], ["as"], ["she'd"], ["entered"], ["it."]],
                    "audioSrc": null,
                    "timeStart": 268.87,
                    "timeEnd": 273.17,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=65",
                    "discussionId": 80050,
                    "discussionName": "Lady Meng Jiang - challenge #65",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80050\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80050?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80050",
                    "editUrl": null
                }, {
                    "id": 80051,
                    "position": 66,
                    "content": "But her tears flowed on,",
                    "defaultInput": "",
                    "jsonContent": ["But", "her", "tears", "flowed", "on,"],
                    "solution": [["But"], ["her"], ["tears"], ["flowed"], ["on,"]],
                    "audioSrc": null,
                    "timeStart": 273.17,
                    "timeEnd": 275.01,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=66",
                    "discussionId": 80051,
                    "discussionName": "Lady Meng Jiang - challenge #66",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80051\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80051?complete=0",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80051",
                    "editUrl": null
                }, {
                    "id": 80052,
                    "position": 67,
                    "content": "a reminder of her virtue and defiance.",
                    "defaultInput": "",
                    "jsonContent": ["a", "reminder", "of", "her", "virtue", "and", "defiance."],
                    "solution": [["a"], ["reminder"], ["of"], ["her"], ["virtue"], ["and"], ["defiance."]],
                    "audioSrc": null,
                    "timeStart": 275.01,
                    "timeEnd": 278.27,
                    "hint": null,
                    "hints": [],
                    "explanation": null,
                    "alwaysShowExplanation": true,
                    "nbComments": 0,
                    "url": "https:\/\/dailydictation.com\/exercises\/ted-ed\/lady-meng-jiang.2045\/listen-and-type?challenge=67",
                    "discussionId": 80052,
                    "discussionName": "Lady Meng Jiang - challenge #67",
                    "discussionUrl": "https:\/\/dailydictation.com\/discussions\/80052\/list",
                    "completeUrl": "https:\/\/dailydictation.com\/api\/user\/save-challenge\/80052?complete=1",
                    "updateNoteUrl": "https:\/\/dailydictation.com\/api\/user\/update-challenge-note\/80052",
                    "editUrl": null
                }];

// =============================================
// CẤU HÌNH
// =============================================
const LESSON_ID = new ObjectId('69ea4e0f6e29e5e206acb4d0'); // ← THAY BẰNG ObjectId thật của Lesson trong DB
// Ví dụ: lấy từ MongoDB khi bạn đã tạo Lesson trước

// =============================================
// CHUYỂN ĐỔI
// =============================================
const sentences = rawChallenges.map(challenge => {
  // Xử lý hint: nếu hint là null hoặc hints là mảng rỗng → []
  let hints = [];
  if (challenge.hint && challenge.hint !== null) {
    hints = [challenge.hint];
  } else if (Array.isArray(challenge.hints) && challenge.hints.length > 0) {
    hints = challenge.hints.filter(h => h && typeof h === 'string');
  }

  return {
    lessonId: { $oid: LESSON_ID.toString() },
    order: challenge.position,
    text: challenge.content.trim(),
    hint: hints,
    translation: null,           // bạn có thể thêm sau hoặc để null
    startTime: challenge.timeStart,
    endTime: challenge.timeEnd,

    // Các trường bổ sung (nếu bạn muốn lưu để dùng sau, không bắt buộc theo model hiện tại)
    // Bạn có thể comment nếu không cần
    // originalChallengeId: challenge.id,
    // audioClipUrl: challenge.audioSrc,
    // jsonContent: challenge.jsonContent,
    // solution: challenge.solution,
    // discussionId: challenge.discussionId,
  };
});

// =============================================
// XUẤT RA FILE JSON (dễ import vào MongoDB)
// =============================================
const output = {
  lessonId: { $oid: LESSON_ID.toString() },
  totalSentences: sentences.length,
  sentences: sentences
};

const outputPath = path.join(__dirname, 'sentences-for-lesson-lady-meng-jiang.json');
fs.writeFileSync(outputPath, JSON.stringify(output, null, 2), 'utf8');

console.log(`Đã tạo file: ${outputPath}`);
console.log(`Tổng số câu: ${sentences.length}`);
console.log('Lesson ID được dùng:', LESSON_ID.toString());

// =============================================
// In ra 2 câu đầu để kiểm tra
// =============================================
console.log('\nVí dụ 2 câu đầu mới:');
console.log(JSON.stringify(sentences.slice(0, 2), null, 2));